repos:
  - repo: local
    hooks:
      - id: ct-lint
        name: Chart Testing Lint
        entry: ct lint --all --check-version-increment=false --use-helmignore
        language: system
        pass_filenames: false
        files: ^charts/
        always_run: true
