FROM apache/airflow:2.8.1-python3.11


# Install required Python packages with constraints
RUN pip install --no-cache-dir \
    openmetadata-managed-apis==1.7.2.1 \
    apache-airflow-providers-openlineage==1.2.0 \
    pyarrow==12.0.1

RUN pip show openmetadata-ingestion
RUN pip list | grep fab


EXPOSE 8080
USER airflow
