FROM apache/airflow:2.10.5

USER airflow
RUN apt-get update && apt-get install -y gcc libmysqlclient-dev build-essential


RUN pip install --no-cache-dir \
    openmetadata-ingestion==1.7.1.1 \
    apache-airflow-providers-openlineage==2.3.0 \
    apache-airflow-providers-fab==4.4.0 \
    apache-airflow-providers-mysql==4.3.0 \
    mysqlclient==2.2.0 \
    psycopg2-binary==2.9.9
