apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-reindex
  labels: 
    {{- include "OpenMetadata.labels" . | indent 4 }}
    {{- with .Values.deploymentAnnotations }}
      annotations:
        {{- toYaml . | nindent 4 }}  
    {{- end }}
spec:
  suspend: true
  failedJobsHistoryLimit: 1  
  successfulJobsHistoryLimit: 1 
  jobTemplate:
    metadata:                    
      name: cron-reindex
    spec:
      selector:
      matchLabels: 
      {{- include "OpenMetadata.selectorLabels" . | nindent 6 }}
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          labels:
            {{- include "OpenMetadata.labels" . | indent 8 }}
        spec:
          {{- with .Values.imagePullSecrets  }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          serviceAccountName: {{ include "OpenMetadata.serviceAccountName" . }}
          {{- if not (.Values.automountServiceAccountToken) }}
          automountServiceAccountToken: {{ .Values.automountServiceAccountToken}}
          {{- end }}
          securityContext:  
            {{- toYaml .Values.securityContext | nindent 12 }}
          containers:
            - name: cron-reindex
              securityContext:
                {{- toYaml .Values.podSecurityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              volumeMounts:
              {{- with .Values.extraVolumeMounts }}
                {{- toYaml . | nindent 10 }}
              {{- end }}
              command: 
                {{ include "OpenMetadata.buildReindexCommand" . | nindent 16 }}
              env:
              {{- include "OpenMetadata.configs" . | nindent 16 }}
              {{- with .Values.extraEnvs }}
                {{- toYaml . | nindent 10 }}
              {{- end }}
              envFrom:
                - secretRef:
                    name: {{ include "OpenMetadata.fullname" . }}-config-secret
                - secretRef:
                    name: {{ include "OpenMetadata.fullname" . }}-omd-secret
                      {{- if .Values.openmetadata.config.database.enabled }}
                - secretRef:
                    name: {{ include "OpenMetadata.fullname" . }}-db-secret
                      {{- end }}
                      {{- if .Values.openmetadata.config.elasticsearch.enabled }}
                - secretRef:
                    name: {{ include "OpenMetadata.fullname" . }}-search-secret
                      {{- end }}
                      {{- if .Values.openmetadata.config.authorizer.enabled }}
                - secretRef:
                    name: {{ include "OpenMetadata.fullname" . }}-authorizer-secret
                      {{- end }}
                      {{- if .Values.openmetadata.config.secretsManager.enabled }}
                - secretRef:
                    name: {{ include "OpenMetadata.fullname" . }}-secretsmanager-secret
                      {{- end }}
                      {{- if .Values.openmetadata.config.web.enabled }}
                - secretRef:
                    name: {{ include "OpenMetadata.fullname" . }}-web-secret
                      {{- end }}
                      {{- if .Values.openmetadata.config.authentication.enabled }}
                - secretRef:
                    name: {{ include "OpenMetadata.fullname" . }}-authentication-secret
                      {{- end }}
                      {{- if .Values.openmetadata.config.eventMonitor.enabled }}
                - secretRef:
                    name: {{ include "OpenMetadata.fullname" . }}-eventmonitor-secret
                      {{- end }}
                      {{- if .Values.openmetadata.config.pipelineServiceClientConfig.enabled }}
                - secretRef:
                    name: {{ include "OpenMetadata.fullname" . }}-pipeline-secret
                      {{- end }}
                      {{- if .Values.openmetadata.config.smtpConfig.enableSmtpServer }}
                - secretRef:
                    name: {{ include "OpenMetadata.fullname" . }}-smtp-secret
                      {{- end }}
                      {{- if .Values.openmetadata.config.jwtTokenConfiguration.enabled }}
                - secretRef:
                    name: {{ include "OpenMetadata.fullname" . }}-jwt-secret
                      {{- end }}
                      {{- with .Values.openmetadata.config.fernetkey }}
                      {{- if not .secretRef }}
                - secretRef:
                    name: {{ include "OpenMetadata.fullname" $ }}-fernetkey-secret
                      {{- end }}
                      {{- end }}
                      {{- with .Values.envFrom }}
                        {{- toYaml . | nindent 10 }}
                      {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
            {{- if .Values.sidecars }}
              {{- include "tplvalues.render" (dict "value" .Values.sidecars "context" $) | nindent 8 }}
            {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}  
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
          {{- end }}                     
          restartPolicy: OnFailure
  schedule: "0/5 * * * *"