{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "OpenMetadata.fullname" . }}-networkpolicy
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "OpenMetadata.labels" . | indent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: openmetadata
  podSelector:
    matchLabels: {{- include "OpenMetadata.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
    # Allow inbound connections
  ingress:
    - ports:
      - port: {{ .Values.service.port }}
      - port: {{ .Values.service.adminPort }}
{{- end }}
