apiVersion: v1
kind: Service
metadata:
  name: fuseki
  namespace: {{ .Release.Namespace }}
  labels:
    app: fuseki
    app.kubernetes.io/name: fuseki
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: fuseki
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
