executor: KubernetesExecutor

images:
  airflow:
    repository: apache/airflow
    tag: 2.7.3
    pullPolicy: IfNotPresent

airflow:
  config:
    AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgresql.daap-dev.svc.cluster.local/airflow

  extraEnv:
    - name: AIRFLOW__CORE__FERNET_KEY
      valueFrom:
        secretKeyRef:
          name: airflow-secrets
          key: FERNET_KEY
    - name: AIRFLOW__WEBSERVER__SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: airflow-secrets
          key: SECRET_KEY

  requirements: |
    openmetadata-ingestion==1.7.1.1
    apache-airflow-providers-openlineage==2.3.0
    openmetadata-managed-apis==1.7.1.1

web:
  port: 8080
  startupProbe:
    httpGet:
      path: /
      port: 8080
    initialDelaySeconds: 180
    timeoutSeconds: 10
    failureThreshold: 30
    periodSeconds: 10
  livenessProbe:
    httpGet:
      path: /
      port: 8080
    initialDelaySeconds: 180
    timeoutSeconds: 10
    failureThreshold: 30
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /
      port: 8080
    initialDelaySeconds: 180
    timeoutSeconds: 10
    failureThreshold: 30
    periodSeconds: 10


postgresql:
  enabled: true
  auth:
    username: airflow
    password: airflow
    database: airflow

redis:
  enabled: true

triggerer:
  enabled: true

logs:
  persistence:
    enabled: true
    storageClassName: azurefile
    size: 1Gi

dags:
  persistence:
    enabled: true
    storageClassName: azurefile
    size: 1Gi
