name: Config Validation Open Metadata Helm Charts

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
  # pull_request:
  #   paths-ignore:
  #     - '**.md'
  #     - 'LICENSE'
  #     - 'NOTICE'
  pull_request_target:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'

jobs:
  configs-validation:
    name: Kubernetes API versions Matrix
    runs-on: ubuntu-latest
    environment: datree
    env:
      DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        # list whatever Kubernetes API versions here you would like to support
        # Will only run the config validations on the versions which are not EOL
        # Ref - https://endoflife.date/kubernetes
        api_version:
          - '1.24.0'
          - '1.25.0'
          - '1.26.0'
          - '1.27.0'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run Datree Policy Check
        uses: datreeio/action-datree@main
        with:
          path: 'charts/openmetadata'
          cliArguments: '--no-record --schema-version ${{ matrix.api_version }}'
          isHelmChart: true
          helmArguments: '--values .github/workflows/test/openmetadata-values.yaml --kube-version ${{ matrix.api_version }}'
