name: Release Open Metadata Charts

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Add Helm repos
        run: |
          helm repo add opensearch https://opensearch-project.github.io/helm-charts/
          helm repo add mysql https://charts.bitnami.com/bitnami
          helm repo add airflow https://airflow-helm.github.io/charts

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_repo_url: https://helm.open-metadata.org
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
